# Exercício 1 - Ligações para o 911

### Nos EUA, o número 911 é destinado à emergências. O [Kaggle](https://www.kaggle.com/mchirico/montcoalert) disponibilizou dados de ligações para o serviço:

* lat: Variável String, Latitude
* lng: Variável String, Longitude
* desc: Variável String, Descrição da Chamada de Emergência
* zip: Variável String, CEP
* título: Variável String, Título
* timeStamp: Variável String, AAAA-MM-DD HH: MM: SS
* twp: Variável String, Township
* addr: Variável String, Endereço
* e: Variável String, variável Dummy (sempre 1)

### Leia o arquivo csv (911.csv) como um dataframe chamado _calls_

In [38]:
import pandas as pd
import numpy as np

### -_Ler o arquivo_

In [39]:
calls = pd.read_csv('911.csv')
calls.head()
calls

,lat,lng,desc,zip,title,timeStamp,twp,addr,e
0,40.297876,-75.581294,REINDEER CT & DEAD END; NEW HANOVER; Station ...,19525.0,EMS: BACK PAINS/INJURY,2015-12-10 17:40:00,NEW HANOVER,REINDEER CT & DEAD END,1
1,40.258061,-75.264680,BRIAR PATH & WHITEMARSH LN; HATFIELD TOWNSHIP...,19446.0,EMS: DIABETIC EMERGENCY,2015-12-10 17:40:00,HATFIELD TOWNSHIP,BRIAR PATH & WHITEMARSH LN,1
2,40.121182,-75.351975,HAWS AVE; NORRISTOWN; 2015-12-10 @ 14:39:21-St...,19401.0,Fire: GAS-ODOR/LEAK,2015-12-10 17:40:00,NORRISTOWN,HAWS AVE,1
3,40.116153,-75.343513,AIRY ST & SWEDE ST; NORRISTOWN; Station 308A;...,19401.0,EMS: CARDIAC EMERGENCY,2015-12-10 17:40:01,NORRISTOWN,AIRY ST & SWEDE ST,1
4,40.251492,-75.603350,CHERRYWOOD CT & DEAD END; LOWER POTTSGROVE; S...,NaN,EMS: DIZZINESS,2015-12-10 17:40:01,LOWER POTTSGROVE,CHERRYWOOD CT & DEAD END,1
5,40.253473,-75.283245,CANNON AVE & W 9TH ST; LANSDALE; Station 345;...,19446.0,EMS: HEAD INJURY,2015-12-10 17:40:01,LANSDALE,CANNON AVE & W 9TH ST,1
6,40.182111,-75.127795,LAUREL AVE & OAKDALE AVE; HORSHAM; Station 35...,19044.0,EMS: NAUSEA/VOMITING,2015-12-10 17:40:01,HORSHAM,LAUREL AVE & OAKDALE AVE,1
7,40.217286,-75.405182,COLLEGEVILLE RD & LYWISKI RD; SKIPPACK; Stati...,19426.0,EMS: RESPIRATORY EMERGENCY,2015-12-10 17:40:01,SKIPPACK,COLLEGEVILLE RD & LYWISKI RD,1
8,40.289027,-75.399590,MAIN ST & OLD SUMNEYTOWN PIKE; LOWER SALFORD;...,19438.0,EMS: SYNCOPAL EPISODE,2015-12-10 17:40:01,LOWER SALFORD,MAIN ST & OLD SUMNEYTOWN PIKE,1
9,40.102398,-75.291458,BLUEROUTE & RAMP I476 NB TO CHEMICAL RD; PLYM...,19462.0,Traffic: VEHICLE ACCIDENT -,2015-12-10 17:40:01,PLYMOUTH,BLUEROUTE & RAMP I476 NB TO CHEMICAL RD,1
10,40.231990,-75.251891,RT202 PKWY & KNAPP RD; MONTGOMERY; 2015-12-10 ...,NaN,Traffic: VEHICLE ACCIDENT -,2015-12-10 17:40:01,MONTGOMERY,RT202 PKWY & KNAPP RD,1
11,40.084161,-75.308386,BROOK RD & COLWELL LN; PLYMOUTH; 2015-12-10 @ ...,19428.0,Traffic: VEHICLE ACCIDENT -,2015-12-10 17:40:02,PLYMOUTH,BROOK RD & COLWELL LN,1
12,40.174131,-75.098491,BYBERRY AVE & S WARMINSTER RD; UPPER MORELAND;...,19040.0,Traffic: VEHICLE ACCIDENT -,2015-12-10 17:40:02,UPPER MORELAND,BYBERRY AVE & S WARMINSTER RD,1
13,40.062974,-75.135914,OLD YORK RD & VALLEY RD; CHELTENHAM; 2015-12-1...,19027.0,Traffic: VEHICLE ACCIDENT -,2015-12-10 17:40:02,CHELTENHAM,OLD YORK RD & VALLEY RD,1
14,40.097222,-75.376195,SCHUYLKILL EXPY & CROTON RD UNDERPASS; UPPER M...,NaN,Traffic: VEHICLE ACCIDENT -,2015-12-10 17:40:02,UPPER MERION,SCHUYLKILL EXPY & CROTON RD UNDERPASS,1
15,40.223778,-75.235399,STUMP RD & WITCHWOOD DR; MONTGOMERY; 2015-12-1...,18936.0,Traffic: VEHICLE ACCIDENT -,2015-12-10 17:40:02,MONTGOMERY,STUMP RD & WITCHWOOD DR,1
16,40.243258,-75.286552,SUSQUEHANNA AVE & W MAIN ST; LANSDALE; Statio...,19446.0,EMS: RESPIRATORY EMERGENCY,2015-12-10 17:46:01,LANSDALE,SUSQUEHANNA AVE & W MAIN ST,1
17,40.312181,-75.574260,CHARLOTTE ST & MILES RD; NEW HANOVER; Station...,19525.0,EMS: DIZZINESS,2015-12-10 17:47:01,NEW HANOVER,CHARLOTTE ST & MILES RD,1
18,40.114239,-75.338508,PENN ST & ARCH ST; NORRISTOWN; Station 308A; ...,19401.0,EMS: VEHICLE ACCIDENT,2015-12-10 17:47:01,NORRISTOWN,PENN ST & ARCH ST,1
19,40.209337,-75.135266,COUNTY LINE RD & WILLOW DR; HORSHAM; 2015-12-1...,18974.0,Traffic: DISABLED VEHICLE -,2015-12-10 17:47:02,HORSHAM,COUNTY LINE RD & WILLOW DR,1
20,40.114239,-75.338508,PENN ST & ARCH ST; NORRISTOWN; 2015-12-10 @ 17...,19401.0,Traffic: VEHICLE ACCIDENT -,2015-12-10 17:47:02,NORRISTOWN,PENN ST & ARCH ST,1
21,40.117948,-75.209848,CHURCH RD & REDCOAT DR; WHITEMARSH; 2015-12-10...,19031.0,Traffic: DISABLED VEHICLE -,2015-12-10 17:57:02,WHITEMARSH,CHURCH RD & REDCOAT DR,1
22,40.199006,-75.300058,LILAC CT & PRIMROSE DR; UPPER GWYNEDD; 2015-12...,19446.0,Fire: APPLIANCE FIRE,2015-12-10 18:02:01,UPPER GWYNEDD,LILAC CT & PRIMROSE DR,1
23,40.143326,-75.422819,RT422 & PAWLINGS RD OVERPASS; LOWER PROVIDENC...,NaN,Traffic: DISABLED VEHICLE -,2015-12-10 18:02:02,LOWER PROVIDENCE,RT422 & PAWLINGS RD OVERPASS,1
24,40.153268,-75.189558,SUMMIT AVE & RT309 UNDERPASS; UPPER DUBLIN; 20...,NaN,Traffic: VEHICLE ACCIDENT -,2015-12-10 18:02:02,UPPER DUBLIN,SUMMIT AVE & RT309 UNDERPASS,1
25,40.133037,-75.408463,SHANNONDELL DR & SHANNONDELL BLVD; LOWER PROV...,19403.0,EMS: GENERAL WEAKNESS,2015-12-10 18:06:25,LOWER PROVIDENCE,SHANNONDELL DR & SHANNONDELL BLVD,1
26,40.155283,-75.264230,PENLLYN BLUE BELL PIKE & VILLAGE CIR; WHITPAI...,19422.0,EMS: HEAD INJURY,2015-12-10 18:06:25,WHITPAIN,PENLLYN BLUE BELL PIKE & VILLAGE CIR,1
27,40.028903,-75.351822,EDENTON PL & DURHAM DR; DELAWARE COUNTY; 2015-...,19085.0,Fire: CARBON MONOXIDE DETECTOR,2015-12-10 18:06:25,DELAWARE COUNTY,EDENTON PL & DURHAM DR,1
28,40.097222,-75.376195,SCHUYLKILL EXPY & WEADLEY RD OVERPASS; UPPER M...,NaN,Traffic: VEHICLE ACCIDENT -,2015-12-10 18:06:26,UPPER MERION,SCHUYLKILL EXPY & WEADLEY RD OVERPASS,1
29,40.209337,-75.135266,COUNTY LINE RD & WILLOW DR; HORSHAM; 2015-12-1...,18974.0,Traffic: DISABLED VEHICLE -,2015-12-10 18:11:01,HORSHAM,COUNTY LINE RD & WILLOW DR,1
...,...,...,...,...,...,...,...,...,...
99462,40.274137,-75.660469,UPLAND SQUARE DR & SELL RD; WEST POTTSGROVE; ...,19464.0,EMS: UNKNOWN MEDICAL EMERGENCY,2016-08-24 09:41:00,WEST POTTSGROVE,UPLAND SQUARE DR & SELL RD,1
99463,40.254768,-75.660459,SHOEMAKER RD & ROBINSON ST; POTTSTOWN; Statio...,19464.0,EMS: UNKNOWN MEDICAL EMERGENCY,2016-08-24 09:42:00,POTTSTOWN,SHOEMAKER RD & ROBINSON ST,1
99464,40.163730,-75.082753,KAREN LN & BYBERRY RD; UPPER MORELAND; Statio...,19040.0,EMS: FALL VICTIM,2016-08-24 09:51:06,UPPER MORELAND,KAREN LN & BYBERRY RD,1
99465,40.114928,-75.340307,AIRY ST & GREEN ST; NORRISTOWN; Station 308A;...,19401.0,EMS: RESPIRATORY EMERGENCY,2016-08-24 09:56:13,NORRISTOWN,AIRY ST & GREEN ST,1
99466,40.159820,-75.288436,WENTZ RD & SILO CIR; WHITPAIN; Station 385; 2...,19422.0,EMS: NAUSEA/VOMITING,2016-08-24 10:01:00,WHITPAIN,WENTZ RD & SILO CIR,1
99467,40.255271,-75.340722,WOODS DR & DETWILER RD; TOWAMENCIN; Station 3...,19446.0,EMS: ALTERED MENTAL STATUS,2016-08-24 10:12:01,TOWAMENCIN,WOODS DR & DETWILER RD,1
99468,40.088355,-75.382100,DEKALB PIKE & ALLENDALE RD; UPPER MERION; 2016...,19406.0,Fire: FIRE ALARM,2016-08-24 10:12:01,UPPER MERION,DEKALB PIKE & ALLENDALE RD,1
99469,40.123868,-75.341678,MARKLEY ST & JAMES ST; NORRISTOWN; 2016-08-24 ...,19401.0,Fire: FIRE ALARM,2016-08-24 10:12:01,NORRISTOWN,MARKLEY ST & JAMES ST,1
99470,40.185798,-75.536484,WALNUT ST & S 5TH AVE; ROYERSFORD; Station 32...,19468.0,EMS: ALTERED MENTAL STATUS,2016-08-24 10:17:01,ROYERSFORD,WALNUT ST & S 5TH AVE,1
99471,40.000763,-75.279769,WYNNEWOOD RD & W OLD WYNNEWOOD RD; LOWER MERI...,19096.0,EMS: RESPIRATORY EMERGENCY,2016-08-24 10:17:01,LOWER MERION,WYNNEWOOD RD & W OLD WYNNEWOOD RD,1
99472,40.129398,-75.332213,PINE ST & W ROBERTS ST; NORRISTOWN; Station 3...,19401.0,EMS: CARDIAC EMERGENCY,2016-08-24 10:22:00,NORRISTOWN,PINE ST & W ROBERTS ST,1
99473,40.133533,-75.056460,BUCK RD & WAVERLY LN; BRYN ATHYN; Station 355...,19009.0,EMS: GENERAL WEAKNESS,2016-08-24 10:27:01,BRYN ATHYN,BUCK RD & WAVERLY LN,1
99474,40.078678,-75.086943,HUNTINGDON PIKE & FILLMORE ST; ROCKLEDGE; Sta...,19046.0,EMS: SEIZURES,2016-08-24 10:27:01,ROCKLEDGE,HUNTINGDON PIKE & FILLMORE ST,1
99475,40.133715,-75.229630,SHEAFF LN & WHITEMARSH VALLEY RD; WHITEMARSH; ...,19034.0,Traffic: VEHICLE ACCIDENT -,2016-08-24 10:32:01,WHITEMARSH,SHEAFF LN & WHITEMARSH VALLEY RD,1
99476,40.257820,-75.624294,PARK DR & N ADAMS ST; POTTSTOWN; Station 329;...,19464.0,EMS: RESPIRATORY EMERGENCY,2016-08-24 10:47:00,POTTSTOWN,PARK DR & N ADAMS ST,1
99477,40.095652,-75.244877,FOX HOUND DR & MARBLE HL; WHITEMARSH; Station...,19444.0,EMS: SUBJECT IN PAIN,2016-08-24 10:47:00,WHITEMARSH,FOX HOUND DR & MARBLE HL,1
99478,40.100344,-75.293955,CHEMICAL RD & GALLAGHER RD; PLYMOUTH; 2016-08-...,19462.0,Traffic: VEHICLE ACCIDENT -,2016-08-24 10:47:02,PLYMOUTH,CHEMICAL RD & GALLAGHER RD,1
99479,40.221227,-75.288737,SUMNEYTOWN PIKE & RR OVERPASS; UPPER GWYNEDD;...,NaN,EMS: CARDIAC EMERGENCY,2016-08-24 10:52:01,UPPER GWYNEDD,SUMNEYTOWN PIKE & RR OVERPASS,1
99480,40.221227,-75.288737,SUMNEYTOWN PIKE & RR OVERPASS; UPPER GWYNEDD;...,NaN,EMS: DIABETIC EMERGENCY,2016-08-24 10:52:01,UPPER GWYNEDD,SUMNEYTOWN PIKE & RR OVERPASS,1
99481,40.221227,-75.288737,SUMNEYTOWN PIKE & RR OVERPASS; UPPER GWYNEDD;...,NaN,EMS: DIZZINESS,2016-08-24 10:52:01,UPPER GWYNEDD,SUMNEYTOWN PIKE & RR OVERPASS,1
99482,40.340072,-75.591709,RT100 SB & E PHILADELPHIA AVE OVERPASS; DOUGLA...,NaN,Traffic: DISABLED VEHICLE -,2016-08-24 10:52:03,DOUGLASS,RT100 SB & E PHILADELPHIA AVE OVERPASS,1
99483,40.084465,-75.390173,DEKALB PIKE & KING OF PRUSSIA RD; UPPER MERIO...,19406.0,EMS: BACK PAINS/INJURY,2016-08-24 10:57:00,UPPER MERION,DEKALB PIKE & KING OF PRUSSIA RD,1
99484,40.133037,-75.408463,SHANNONDELL DR & SHANNONDELL BLVD; LOWER PROVI...,19403.0,Fire: FIRE ALARM,2016-08-24 10:57:00,LOWER PROVIDENCE,SHANNONDELL DR & SHANNONDELL BLVD,1
99485,40.143601,-75.427877,EAGLEVILLE RD & REDTAIL RD; LOWER PROVIDENCE; ...,19403.0,Traffic: DISABLED VEHICLE -,2016-08-24 10:57:01,LOWER PROVIDENCE,EAGLEVILLE RD & REDTAIL RD,1
99486,40.179225,-75.180572,WELSH RD & NORRISTOWN RD; HORSHAM; 2016-08-24 ...,19044.0,Traffic: VEHICLE ACCIDENT -,2016-08-24 11:02:02,HORSHAM,WELSH RD & NORRISTOWN RD,1
99487,40.132869,-75.333515,MARKLEY ST & W LOGAN ST; NORRISTOWN; 2016-08-2...,19401.0,Traffic: VEHICLE ACCIDENT -,2016-08-24 11:06:00,NORRISTOWN,MARKLEY ST & W LOGAN ST,1
99488,40.006974,-75.289080,LANCASTER AVE & RITTENHOUSE PL; LOWER MERION; ...,19003.0,Traffic: VEHICLE ACCIDENT -,2016-08-24 11:07:02,LOWER MERION,LANCASTER AVE & RITTENHOUSE PL,1
99489,40.115429,-75.334679,CHESTNUT ST & WALNUT ST; NORRISTOWN; Station ...,19401.0,EMS: FALL VICTIM,2016-08-24 11:12:00,NORRISTOWN,CHESTNUT ST & WALNUT ST,1
99490,40.186431,-75.192555,WELSH RD & WEBSTER LN; HORSHAM; Station 352; ...,19002.0,EMS: NAUSEA/VOMITING,2016-08-24 11:17:01,HORSHAM,WELSH RD & WEBSTER LN,1
99491,40.207055,-75.317952,MORRIS RD & S BROAD ST; UPPER GWYNEDD; 2016-08...,19446.0,Traffic: VEHICLE ACCIDENT -,2016-08-24 11:17:02,UPPER GWYNEDD,MORRIS RD & S BROAD ST,1

### Quantas linhas e colunas tem o arquivo? Qual a quantidade de memória necessária para carregá-lo?

### -_Mostrar quantidade de linhas e colunas,tipos das colunas e memória usada pelo arquivo_

In [40]:
calls.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99492 entries, 0 to 99491
Data columns (total 9 columns):
lat          99492 non-null float64
lng          99492 non-null float64
desc         99492 non-null object
zip          86637 non-null float64
title        99492 non-null object
timeStamp    99492 non-null object
twp          99449 non-null object
addr         98973 non-null object
e            99492 non-null int64
dtypes: float64(3), int64(1), object(5)
memory usage: 6.8+ MB

### Quais são os top 5 CEPs nas chamadas 911?

### -_Mostrar os 5 CEPs com mais chamados_

In [41]:
calls.zip.value_counts().nlargest(5)

19401.0    6979
19464.0    6643
19403.0    4854
19446.0    4748
19406.0    3174
Name: zip, dtype: int64

### Quais são os 5 principais municípios nas chamadas 911?

### -_Mostrar os 5 municípios com mais chamados_

In [42]:
calls.twp.value_counts().nlargest()

LOWER MERION    8443
ABINGTON        5977
NORRISTOWN      5890
UPPER MERION    5227
CHELTENHAM      4575
Name: twp, dtype: int64

### Quantos códigos de título únicos existem?

### -_Contar quantos códigos de títulos únicos há no arquivo_

In [43]:
calls.title.value_counts().count()

110

### Na coluna _title_ existem Razões / Departamentos especificados antes do código do título. Estes são _"EMS"_, _"Fire"_ e _"Traffic"_. Crie uma nova coluna chamada _Reason_ que conterá esse valor em cada linha

#### Por exemplo, se o valor da coluna do título for EMS: BACK PAINS / BLESSOR, o valor da coluna Reason será EMS.

### -_Criação da coluna Reason separando as Razões/Departamentos da coluna title_

In [44]:
arr = np.array(calls.loc[:,'title'])
calls['Reason'] = [f.split(sep=':')[0] for f in arr]
calls

,lat,lng,desc,zip,title,timeStamp,twp,addr,e,Reason
0,40.297876,-75.581294,REINDEER CT & DEAD END; NEW HANOVER; Station ...,19525.0,EMS: BACK PAINS/INJURY,2015-12-10 17:40:00,NEW HANOVER,REINDEER CT & DEAD END,1,EMS
1,40.258061,-75.264680,BRIAR PATH & WHITEMARSH LN; HATFIELD TOWNSHIP...,19446.0,EMS: DIABETIC EMERGENCY,2015-12-10 17:40:00,HATFIELD TOWNSHIP,BRIAR PATH & WHITEMARSH LN,1,EMS
2,40.121182,-75.351975,HAWS AVE; NORRISTOWN; 2015-12-10 @ 14:39:21-St...,19401.0,Fire: GAS-ODOR/LEAK,2015-12-10 17:40:00,NORRISTOWN,HAWS AVE,1,Fire
3,40.116153,-75.343513,AIRY ST & SWEDE ST; NORRISTOWN; Station 308A;...,19401.0,EMS: CARDIAC EMERGENCY,2015-12-10 17:40:01,NORRISTOWN,AIRY ST & SWEDE ST,1,EMS
4,40.251492,-75.603350,CHERRYWOOD CT & DEAD END; LOWER POTTSGROVE; S...,NaN,EMS: DIZZINESS,2015-12-10 17:40:01,LOWER POTTSGROVE,CHERRYWOOD CT & DEAD END,1,EMS
5,40.253473,-75.283245,CANNON AVE & W 9TH ST; LANSDALE; Station 345;...,19446.0,EMS: HEAD INJURY,2015-12-10 17:40:01,LANSDALE,CANNON AVE & W 9TH ST,1,EMS
6,40.182111,-75.127795,LAUREL AVE & OAKDALE AVE; HORSHAM; Station 35...,19044.0,EMS: NAUSEA/VOMITING,2015-12-10 17:40:01,HORSHAM,LAUREL AVE & OAKDALE AVE,1,EMS
7,40.217286,-75.405182,COLLEGEVILLE RD & LYWISKI RD; SKIPPACK; Stati...,19426.0,EMS: RESPIRATORY EMERGENCY,2015-12-10 17:40:01,SKIPPACK,COLLEGEVILLE RD & LYWISKI RD,1,EMS
8,40.289027,-75.399590,MAIN ST & OLD SUMNEYTOWN PIKE; LOWER SALFORD;...,19438.0,EMS: SYNCOPAL EPISODE,2015-12-10 17:40:01,LOWER SALFORD,MAIN ST & OLD SUMNEYTOWN PIKE,1,EMS
9,40.102398,-75.291458,BLUEROUTE & RAMP I476 NB TO CHEMICAL RD; PLYM...,19462.0,Traffic: VEHICLE ACCIDENT -,2015-12-10 17:40:01,PLYMOUTH,BLUEROUTE & RAMP I476 NB TO CHEMICAL RD,1,Traffic
10,40.231990,-75.251891,RT202 PKWY & KNAPP RD; MONTGOMERY; 2015-12-10 ...,NaN,Traffic: VEHICLE ACCIDENT -,2015-12-10 17:40:01,MONTGOMERY,RT202 PKWY & KNAPP RD,1,Traffic
11,40.084161,-75.308386,BROOK RD & COLWELL LN; PLYMOUTH; 2015-12-10 @ ...,19428.0,Traffic: VEHICLE ACCIDENT -,2015-12-10 17:40:02,PLYMOUTH,BROOK RD & COLWELL LN,1,Traffic
12,40.174131,-75.098491,BYBERRY AVE & S WARMINSTER RD; UPPER MORELAND;...,19040.0,Traffic: VEHICLE ACCIDENT -,2015-12-10 17:40:02,UPPER MORELAND,BYBERRY AVE & S WARMINSTER RD,1,Traffic
13,40.062974,-75.135914,OLD YORK RD & VALLEY RD; CHELTENHAM; 2015-12-1...,19027.0,Traffic: VEHICLE ACCIDENT -,2015-12-10 17:40:02,CHELTENHAM,OLD YORK RD & VALLEY RD,1,Traffic
14,40.097222,-75.376195,SCHUYLKILL EXPY & CROTON RD UNDERPASS; UPPER M...,NaN,Traffic: VEHICLE ACCIDENT -,2015-12-10 17:40:02,UPPER MERION,SCHUYLKILL EXPY & CROTON RD UNDERPASS,1,Traffic
15,40.223778,-75.235399,STUMP RD & WITCHWOOD DR; MONTGOMERY; 2015-12-1...,18936.0,Traffic: VEHICLE ACCIDENT -,2015-12-10 17:40:02,MONTGOMERY,STUMP RD & WITCHWOOD DR,1,Traffic
16,40.243258,-75.286552,SUSQUEHANNA AVE & W MAIN ST; LANSDALE; Statio...,19446.0,EMS: RESPIRATORY EMERGENCY,2015-12-10 17:46:01,LANSDALE,SUSQUEHANNA AVE & W MAIN ST,1,EMS
17,40.312181,-75.574260,CHARLOTTE ST & MILES RD; NEW HANOVER; Station...,19525.0,EMS: DIZZINESS,2015-12-10 17:47:01,NEW HANOVER,CHARLOTTE ST & MILES RD,1,EMS
18,40.114239,-75.338508,PENN ST & ARCH ST; NORRISTOWN; Station 308A; ...,19401.0,EMS: VEHICLE ACCIDENT,2015-12-10 17:47:01,NORRISTOWN,PENN ST & ARCH ST,1,EMS
19,40.209337,-75.135266,COUNTY LINE RD & WILLOW DR; HORSHAM; 2015-12-1...,18974.0,Traffic: DISABLED VEHICLE -,2015-12-10 17:47:02,HORSHAM,COUNTY LINE RD & WILLOW DR,1,Traffic
20,40.114239,-75.338508,PENN ST & ARCH ST; NORRISTOWN; 2015-12-10 @ 17...,19401.0,Traffic: VEHICLE ACCIDENT -,2015-12-10 17:47:02,NORRISTOWN,PENN ST & ARCH ST,1,Traffic
21,40.117948,-75.209848,CHURCH RD & REDCOAT DR; WHITEMARSH; 2015-12-10...,19031.0,Traffic: DISABLED VEHICLE -,2015-12-10 17:57:02,WHITEMARSH,CHURCH RD & REDCOAT DR,1,Traffic
22,40.199006,-75.300058,LILAC CT & PRIMROSE DR; UPPER GWYNEDD; 2015-12...,19446.0,Fire: APPLIANCE FIRE,2015-12-10 18:02:01,UPPER GWYNEDD,LILAC CT & PRIMROSE DR,1,Fire
23,40.143326,-75.422819,RT422 & PAWLINGS RD OVERPASS; LOWER PROVIDENC...,NaN,Traffic: DISABLED VEHICLE -,2015-12-10 18:02:02,LOWER PROVIDENCE,RT422 & PAWLINGS RD OVERPASS,1,Traffic
24,40.153268,-75.189558,SUMMIT AVE & RT309 UNDERPASS; UPPER DUBLIN; 20...,NaN,Traffic: VEHICLE ACCIDENT -,2015-12-10 18:02:02,UPPER DUBLIN,SUMMIT AVE & RT309 UNDERPASS,1,Traffic
25,40.133037,-75.408463,SHANNONDELL DR & SHANNONDELL BLVD; LOWER PROV...,19403.0,EMS: GENERAL WEAKNESS,2015-12-10 18:06:25,LOWER PROVIDENCE,SHANNONDELL DR & SHANNONDELL BLVD,1,EMS
26,40.155283,-75.264230,PENLLYN BLUE BELL PIKE & VILLAGE CIR; WHITPAI...,19422.0,EMS: HEAD INJURY,2015-12-10 18:06:25,WHITPAIN,PENLLYN BLUE BELL PIKE & VILLAGE CIR,1,EMS
27,40.028903,-75.351822,EDENTON PL & DURHAM DR; DELAWARE COUNTY; 2015-...,19085.0,Fire: CARBON MONOXIDE DETECTOR,2015-12-10 18:06:25,DELAWARE COUNTY,EDENTON PL & DURHAM DR,1,Fire
28,40.097222,-75.376195,SCHUYLKILL EXPY & WEADLEY RD OVERPASS; UPPER M...,NaN,Traffic: VEHICLE ACCIDENT -,2015-12-10 18:06:26,UPPER MERION,SCHUYLKILL EXPY & WEADLEY RD OVERPASS,1,Traffic
29,40.209337,-75.135266,COUNTY LINE RD & WILLOW DR; HORSHAM; 2015-12-1...,18974.0,Traffic: DISABLED VEHICLE -,2015-12-10 18:11:01,HORSHAM,COUNTY LINE RD & WILLOW DR,1,Traffic
...,...,...,...,...,...,...,...,...,...,...
99462,40.274137,-75.660469,UPLAND SQUARE DR & SELL RD; WEST POTTSGROVE; ...,19464.0,EMS: UNKNOWN MEDICAL EMERGENCY,2016-08-24 09:41:00,WEST POTTSGROVE,UPLAND SQUARE DR & SELL RD,1,EMS
99463,40.254768,-75.660459,SHOEMAKER RD & ROBINSON ST; POTTSTOWN; Statio...,19464.0,EMS: UNKNOWN MEDICAL EMERGENCY,2016-08-24 09:42:00,POTTSTOWN,SHOEMAKER RD & ROBINSON ST,1,EMS
99464,40.163730,-75.082753,KAREN LN & BYBERRY RD; UPPER MORELAND; Statio...,19040.0,EMS: FALL VICTIM,2016-08-24 09:51:06,UPPER MORELAND,KAREN LN & BYBERRY RD,1,EMS
99465,40.114928,-75.340307,AIRY ST & GREEN ST; NORRISTOWN; Station 308A;...,19401.0,EMS: RESPIRATORY EMERGENCY,2016-08-24 09:56:13,NORRISTOWN,AIRY ST & GREEN ST,1,EMS
99466,40.159820,-75.288436,WENTZ RD & SILO CIR; WHITPAIN; Station 385; 2...,19422.0,EMS: NAUSEA/VOMITING,2016-08-24 10:01:00,WHITPAIN,WENTZ RD & SILO CIR,1,EMS
99467,40.255271,-75.340722,WOODS DR & DETWILER RD; TOWAMENCIN; Station 3...,19446.0,EMS: ALTERED MENTAL STATUS,2016-08-24 10:12:01,TOWAMENCIN,WOODS DR & DETWILER RD,1,EMS
99468,40.088355,-75.382100,DEKALB PIKE & ALLENDALE RD; UPPER MERION; 2016...,19406.0,Fire: FIRE ALARM,2016-08-24 10:12:01,UPPER MERION,DEKALB PIKE & ALLENDALE RD,1,Fire
99469,40.123868,-75.341678,MARKLEY ST & JAMES ST; NORRISTOWN; 2016-08-24 ...,19401.0,Fire: FIRE ALARM,2016-08-24 10:12:01,NORRISTOWN,MARKLEY ST & JAMES ST,1,Fire
99470,40.185798,-75.536484,WALNUT ST & S 5TH AVE; ROYERSFORD; Station 32...,19468.0,EMS: ALTERED MENTAL STATUS,2016-08-24 10:17:01,ROYERSFORD,WALNUT ST & S 5TH AVE,1,EMS
99471,40.000763,-75.279769,WYNNEWOOD RD & W OLD WYNNEWOOD RD; LOWER MERI...,19096.0,EMS: RESPIRATORY EMERGENCY,2016-08-24 10:17:01,LOWER MERION,WYNNEWOOD RD & W OLD WYNNEWOOD RD,1,EMS
99472,40.129398,-75.332213,PINE ST & W ROBERTS ST; NORRISTOWN; Station 3...,19401.0,EMS: CARDIAC EMERGENCY,2016-08-24 10:22:00,NORRISTOWN,PINE ST & W ROBERTS ST,1,EMS
99473,40.133533,-75.056460,BUCK RD & WAVERLY LN; BRYN ATHYN; Station 355...,19009.0,EMS: GENERAL WEAKNESS,2016-08-24 10:27:01,BRYN ATHYN,BUCK RD & WAVERLY LN,1,EMS
99474,40.078678,-75.086943,HUNTINGDON PIKE & FILLMORE ST; ROCKLEDGE; Sta...,19046.0,EMS: SEIZURES,2016-08-24 10:27:01,ROCKLEDGE,HUNTINGDON PIKE & FILLMORE ST,1,EMS
99475,40.133715,-75.229630,SHEAFF LN & WHITEMARSH VALLEY RD; WHITEMARSH; ...,19034.0,Traffic: VEHICLE ACCIDENT -,2016-08-24 10:32:01,WHITEMARSH,SHEAFF LN & WHITEMARSH VALLEY RD,1,Traffic
99476,40.257820,-75.624294,PARK DR & N ADAMS ST; POTTSTOWN; Station 329;...,19464.0,EMS: RESPIRATORY EMERGENCY,2016-08-24 10:47:00,POTTSTOWN,PARK DR & N ADAMS ST,1,EMS
99477,40.095652,-75.244877,FOX HOUND DR & MARBLE HL; WHITEMARSH; Station...,19444.0,EMS: SUBJECT IN PAIN,2016-08-24 10:47:00,WHITEMARSH,FOX HOUND DR & MARBLE HL,1,EMS
99478,40.100344,-75.293955,CHEMICAL RD & GALLAGHER RD; PLYMOUTH; 2016-08-...,19462.0,Traffic: VEHICLE ACCIDENT -,2016-08-24 10:47:02,PLYMOUTH,CHEMICAL RD & GALLAGHER RD,1,Traffic
99479,40.221227,-75.288737,SUMNEYTOWN PIKE & RR OVERPASS; UPPER GWYNEDD;...,NaN,EMS: CARDIAC EMERGENCY,2016-08-24 10:52:01,UPPER GWYNEDD,SUMNEYTOWN PIKE & RR OVERPASS,1,EMS
99480,40.221227,-75.288737,SUMNEYTOWN PIKE & RR OVERPASS; UPPER GWYNEDD;...,NaN,EMS: DIABETIC EMERGENCY,2016-08-24 10:52:01,UPPER GWYNEDD,SUMNEYTOWN PIKE & RR OVERPASS,1,EMS
99481,40.221227,-75.288737,SUMNEYTOWN PIKE & RR OVERPASS; UPPER GWYNEDD;...,NaN,EMS: DIZZINESS,2016-08-24 10:52:01,UPPER GWYNEDD,SUMNEYTOWN PIKE & RR OVERPASS,1,EMS
99482,40.340072,-75.591709,RT100 SB & E PHILADELPHIA AVE OVERPASS; DOUGLA...,NaN,Traffic: DISABLED VEHICLE -,2016-08-24 10:52:03,DOUGLASS,RT100 SB & E PHILADELPHIA AVE OVERPASS,1,Traffic
99483,40.084465,-75.390173,DEKALB PIKE & KING OF PRUSSIA RD; UPPER MERIO...,19406.0,EMS: BACK PAINS/INJURY,2016-08-24 10:57:00,UPPER MERION,DEKALB PIKE & KING OF PRUSSIA RD,1,EMS
99484,40.133037,-75.408463,SHANNONDELL DR & SHANNONDELL BLVD; LOWER PROVI...,19403.0,Fire: FIRE ALARM,2016-08-24 10:57:00,LOWER PROVIDENCE,SHANNONDELL DR & SHANNONDELL BLVD,1,Fire
99485,40.143601,-75.427877,EAGLEVILLE RD & REDTAIL RD; LOWER PROVIDENCE; ...,19403.0,Traffic: DISABLED VEHICLE -,2016-08-24 10:57:01,LOWER PROVIDENCE,EAGLEVILLE RD & REDTAIL RD,1,Traffic
99486,40.179225,-75.180572,WELSH RD & NORRISTOWN RD; HORSHAM; 2016-08-24 ...,19044.0,Traffic: VEHICLE ACCIDENT -,2016-08-24 11:02:02,HORSHAM,WELSH RD & NORRISTOWN RD,1,Traffic
99487,40.132869,-75.333515,MARKLEY ST & W LOGAN ST; NORRISTOWN; 2016-08-2...,19401.0,Traffic: VEHICLE ACCIDENT -,2016-08-24 11:06:00,NORRISTOWN,MARKLEY ST & W LOGAN ST,1,Traffic
99488,40.006974,-75.289080,LANCASTER AVE & RITTENHOUSE PL; LOWER MERION; ...,19003.0,Traffic: VEHICLE ACCIDENT -,2016-08-24 11:07:02,LOWER MERION,LANCASTER AVE & RITTENHOUSE PL,1,Traffic
99489,40.115429,-75.334679,CHESTNUT ST & WALNUT ST; NORRISTOWN; Station ...,19401.0,EMS: FALL VICTIM,2016-08-24 11:12:00,NORRISTOWN,CHESTNUT ST & WALNUT ST,1,EMS
99490,40.186431,-75.192555,WELSH RD & WEBSTER LN; HORSHAM; Station 352; ...,19002.0,EMS: NAUSEA/VOMITING,2016-08-24 11:17:01,HORSHAM,WELSH RD & WEBSTER LN,1,EMS
99491,40.207055,-75.317952,MORRIS RD & S BROAD ST; UPPER GWYNEDD; 2016-08...,19446.0,Traffic: VEHICLE ACCIDENT -,2016-08-24 11:17:02,UPPER GWYNEDD,MORRIS RD & S BROAD ST,1,Traffic

### Qual é a razão mais comum para uma chamada do 911 com base nessa nova coluna?

### -_Mostrar a razão mais comum da coluna Reason_

In [45]:
calls.Reason.value_counts().nlargest(1)

EMS    48877
Name: Reason, dtype: int64

### Qual é o tipo de dados dos objetos na coluna _timeStamp_?

### -_Mostrar o tipo de dados da coluna timeStamp_

In [46]:
calls.timeStamp.dtype

dtype('O')

### Converta a coluna _timeStamp_ para DateTime. Use [pd.to_datetime](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.to_datetime.html) para essa operação.

### -_Conversão da coluna timeStamp para DateTime_

In [47]:
calls.timeStamp = pd.to_datetime(calls.timeStamp)
calls.timeStamp.dtype

dtype('<M8[ns]')

### Crie 3 novas colunas chamadas _Hour_, _Month_ e _Day of Week_. Você criará essas colunas com base na coluna timeStamp

### -_Separação de horas, meses e dias da semana da coluna timestamp e criado colunas novas_

In [48]:
calls['Hour'] = calls['timeStamp'].dt.hour
calls['Month'] = calls['timeStamp'].dt.month
calls['Day_of_Week'] = calls['timeStamp'].dt.dayofweek
calls

,lat,lng,desc,zip,title,timeStamp,twp,addr,e,Reason,Hour,Month,Day_of_Week
0,40.297876,-75.581294,REINDEER CT & DEAD END; NEW HANOVER; Station ...,19525.0,EMS: BACK PAINS/INJURY,2015-12-10 17:40:00,NEW HANOVER,REINDEER CT & DEAD END,1,EMS,17,12,3
1,40.258061,-75.264680,BRIAR PATH & WHITEMARSH LN; HATFIELD TOWNSHIP...,19446.0,EMS: DIABETIC EMERGENCY,2015-12-10 17:40:00,HATFIELD TOWNSHIP,BRIAR PATH & WHITEMARSH LN,1,EMS,17,12,3
2,40.121182,-75.351975,HAWS AVE; NORRISTOWN; 2015-12-10 @ 14:39:21-St...,19401.0,Fire: GAS-ODOR/LEAK,2015-12-10 17:40:00,NORRISTOWN,HAWS AVE,1,Fire,17,12,3
3,40.116153,-75.343513,AIRY ST & SWEDE ST; NORRISTOWN; Station 308A;...,19401.0,EMS: CARDIAC EMERGENCY,2015-12-10 17:40:01,NORRISTOWN,AIRY ST & SWEDE ST,1,EMS,17,12,3
4,40.251492,-75.603350,CHERRYWOOD CT & DEAD END; LOWER POTTSGROVE; S...,NaN,EMS: DIZZINESS,2015-12-10 17:40:01,LOWER POTTSGROVE,CHERRYWOOD CT & DEAD END,1,EMS,17,12,3
5,40.253473,-75.283245,CANNON AVE & W 9TH ST; LANSDALE; Station 345;...,19446.0,EMS: HEAD INJURY,2015-12-10 17:40:01,LANSDALE,CANNON AVE & W 9TH ST,1,EMS,17,12,3
6,40.182111,-75.127795,LAUREL AVE & OAKDALE AVE; HORSHAM; Station 35...,19044.0,EMS: NAUSEA/VOMITING,2015-12-10 17:40:01,HORSHAM,LAUREL AVE & OAKDALE AVE,1,EMS,17,12,3
7,40.217286,-75.405182,COLLEGEVILLE RD & LYWISKI RD; SKIPPACK; Stati...,19426.0,EMS: RESPIRATORY EMERGENCY,2015-12-10 17:40:01,SKIPPACK,COLLEGEVILLE RD & LYWISKI RD,1,EMS,17,12,3
8,40.289027,-75.399590,MAIN ST & OLD SUMNEYTOWN PIKE; LOWER SALFORD;...,19438.0,EMS: SYNCOPAL EPISODE,2015-12-10 17:40:01,LOWER SALFORD,MAIN ST & OLD SUMNEYTOWN PIKE,1,EMS,17,12,3
9,40.102398,-75.291458,BLUEROUTE & RAMP I476 NB TO CHEMICAL RD; PLYM...,19462.0,Traffic: VEHICLE ACCIDENT -,2015-12-10 17:40:01,PLYMOUTH,BLUEROUTE & RAMP I476 NB TO CHEMICAL RD,1,Traffic,17,12,3
10,40.231990,-75.251891,RT202 PKWY & KNAPP RD; MONTGOMERY; 2015-12-10 ...,NaN,Traffic: VEHICLE ACCIDENT -,2015-12-10 17:40:01,MONTGOMERY,RT202 PKWY & KNAPP RD,1,Traffic,17,12,3
11,40.084161,-75.308386,BROOK RD & COLWELL LN; PLYMOUTH; 2015-12-10 @ ...,19428.0,Traffic: VEHICLE ACCIDENT -,2015-12-10 17:40:02,PLYMOUTH,BROOK RD & COLWELL LN,1,Traffic,17,12,3
12,40.174131,-75.098491,BYBERRY AVE & S WARMINSTER RD; UPPER MORELAND;...,19040.0,Traffic: VEHICLE ACCIDENT -,2015-12-10 17:40:02,UPPER MORELAND,BYBERRY AVE & S WARMINSTER RD,1,Traffic,17,12,3
13,40.062974,-75.135914,OLD YORK RD & VALLEY RD; CHELTENHAM; 2015-12-1...,19027.0,Traffic: VEHICLE ACCIDENT -,2015-12-10 17:40:02,CHELTENHAM,OLD YORK RD & VALLEY RD,1,Traffic,17,12,3
14,40.097222,-75.376195,SCHUYLKILL EXPY & CROTON RD UNDERPASS; UPPER M...,NaN,Traffic: VEHICLE ACCIDENT -,2015-12-10 17:40:02,UPPER MERION,SCHUYLKILL EXPY & CROTON RD UNDERPASS,1,Traffic,17,12,3
15,40.223778,-75.235399,STUMP RD & WITCHWOOD DR; MONTGOMERY; 2015-12-1...,18936.0,Traffic: VEHICLE ACCIDENT -,2015-12-10 17:40:02,MONTGOMERY,STUMP RD & WITCHWOOD DR,1,Traffic,17,12,3
16,40.243258,-75.286552,SUSQUEHANNA AVE & W MAIN ST; LANSDALE; Statio...,19446.0,EMS: RESPIRATORY EMERGENCY,2015-12-10 17:46:01,LANSDALE,SUSQUEHANNA AVE & W MAIN ST,1,EMS,17,12,3
17,40.312181,-75.574260,CHARLOTTE ST & MILES RD; NEW HANOVER; Station...,19525.0,EMS: DIZZINESS,2015-12-10 17:47:01,NEW HANOVER,CHARLOTTE ST & MILES RD,1,EMS,17,12,3
18,40.114239,-75.338508,PENN ST & ARCH ST; NORRISTOWN; Station 308A; ...,19401.0,EMS: VEHICLE ACCIDENT,2015-12-10 17:47:01,NORRISTOWN,PENN ST & ARCH ST,1,EMS,17,12,3
19,40.209337,-75.135266,COUNTY LINE RD & WILLOW DR; HORSHAM; 2015-12-1...,18974.0,Traffic: DISABLED VEHICLE -,2015-12-10 17:47:02,HORSHAM,COUNTY LINE RD & WILLOW DR,1,Traffic,17,12,3
20,40.114239,-75.338508,PENN ST & ARCH ST; NORRISTOWN; 2015-12-10 @ 17...,19401.0,Traffic: VEHICLE ACCIDENT -,2015-12-10 17:47:02,NORRISTOWN,PENN ST & ARCH ST,1,Traffic,17,12,3
21,40.117948,-75.209848,CHURCH RD & REDCOAT DR; WHITEMARSH; 2015-12-10...,19031.0,Traffic: DISABLED VEHICLE -,2015-12-10 17:57:02,WHITEMARSH,CHURCH RD & REDCOAT DR,1,Traffic,17,12,3
22,40.199006,-75.300058,LILAC CT & PRIMROSE DR; UPPER GWYNEDD; 2015-12...,19446.0,Fire: APPLIANCE FIRE,2015-12-10 18:02:01,UPPER GWYNEDD,LILAC CT & PRIMROSE DR,1,Fire,18,12,3
23,40.143326,-75.422819,RT422 & PAWLINGS RD OVERPASS; LOWER PROVIDENC...,NaN,Traffic: DISABLED VEHICLE -,2015-12-10 18:02:02,LOWER PROVIDENCE,RT422 & PAWLINGS RD OVERPASS,1,Traffic,18,12,3
24,40.153268,-75.189558,SUMMIT AVE & RT309 UNDERPASS; UPPER DUBLIN; 20...,NaN,Traffic: VEHICLE ACCIDENT -,2015-12-10 18:02:02,UPPER DUBLIN,SUMMIT AVE & RT309 UNDERPASS,1,Traffic,18,12,3
25,40.133037,-75.408463,SHANNONDELL DR & SHANNONDELL BLVD; LOWER PROV...,19403.0,EMS: GENERAL WEAKNESS,2015-12-10 18:06:25,LOWER PROVIDENCE,SHANNONDELL DR & SHANNONDELL BLVD,1,EMS,18,12,3
26,40.155283,-75.264230,PENLLYN BLUE BELL PIKE & VILLAGE CIR; WHITPAI...,19422.0,EMS: HEAD INJURY,2015-12-10 18:06:25,WHITPAIN,PENLLYN BLUE BELL PIKE & VILLAGE CIR,1,EMS,18,12,3
27,40.028903,-75.351822,EDENTON PL & DURHAM DR; DELAWARE COUNTY; 2015-...,19085.0,Fire: CARBON MONOXIDE DETECTOR,2015-12-10 18:06:25,DELAWARE COUNTY,EDENTON PL & DURHAM DR,1,Fire,18,12,3
28,40.097222,-75.376195,SCHUYLKILL EXPY & WEADLEY RD OVERPASS; UPPER M...,NaN,Traffic: VEHICLE ACCIDENT -,2015-12-10 18:06:26,UPPER MERION,SCHUYLKILL EXPY & WEADLEY RD OVERPASS,1,Traffic,18,12,3
29,40.209337,-75.135266,COUNTY LINE RD & WILLOW DR; HORSHAM; 2015-12-1...,18974.0,Traffic: DISABLED VEHICLE -,2015-12-10 18:11:01,HORSHAM,COUNTY LINE RD & WILLOW DR,1,Traffic,18,12,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
99462,40.274137,-75.660469,UPLAND SQUARE DR & SELL RD; WEST POTTSGROVE; ...,19464.0,EMS: UNKNOWN MEDICAL EMERGENCY,2016-08-24 09:41:00,WEST POTTSGROVE,UPLAND SQUARE DR & SELL RD,1,EMS,9,8,2
99463,40.254768,-75.660459,SHOEMAKER RD & ROBINSON ST; POTTSTOWN; Statio...,19464.0,EMS: UNKNOWN MEDICAL EMERGENCY,2016-08-24 09:42:00,POTTSTOWN,SHOEMAKER RD & ROBINSON ST,1,EMS,9,8,2
99464,40.163730,-75.082753,KAREN LN & BYBERRY RD; UPPER MORELAND; Statio...,19040.0,EMS: FALL VICTIM,2016-08-24 09:51:06,UPPER MORELAND,KAREN LN & BYBERRY RD,1,EMS,9,8,2
99465,40.114928,-75.340307,AIRY ST & GREEN ST; NORRISTOWN; Station 308A;...,19401.0,EMS: RESPIRATORY EMERGENCY,2016-08-24 09:56:13,NORRISTOWN,AIRY ST & GREEN ST,1,EMS,9,8,2
99466,40.159820,-75.288436,WENTZ RD & SILO CIR; WHITPAIN; Station 385; 2...,19422.0,EMS: NAUSEA/VOMITING,2016-08-24 10:01:00,WHITPAIN,WENTZ RD & SILO CIR,1,EMS,10,8,2
99467,40.255271,-75.340722,WOODS DR & DETWILER RD; TOWAMENCIN; Station 3...,19446.0,EMS: ALTERED MENTAL STATUS,2016-08-24 10:12:01,TOWAMENCIN,WOODS DR & DETWILER RD,1,EMS,10,8,2
99468,40.088355,-75.382100,DEKALB PIKE & ALLENDALE RD; UPPER MERION; 2016...,19406.0,Fire: FIRE ALARM,2016-08-24 10:12:01,UPPER MERION,DEKALB PIKE & ALLENDALE RD,1,Fire,10,8,2
99469,40.123868,-75.341678,MARKLEY ST & JAMES ST; NORRISTOWN; 2016-08-24 ...,19401.0,Fire: FIRE ALARM,2016-08-24 10:12:01,NORRISTOWN,MARKLEY ST & JAMES ST,1,Fire,10,8,2
99470,40.185798,-75.536484,WALNUT ST & S 5TH AVE; ROYERSFORD; Station 32...,19468.0,EMS: ALTERED MENTAL STATUS,2016-08-24 10:17:01,ROYERSFORD,WALNUT ST & S 5TH AVE,1,EMS,10,8,2
99471,40.000763,-75.279769,WYNNEWOOD RD & W OLD WYNNEWOOD RD; LOWER MERI...,19096.0,EMS: RESPIRATORY EMERGENCY,2016-08-24 10:17:01,LOWER MERION,WYNNEWOOD RD & W OLD WYNNEWOOD RD,1,EMS,10,8,2
99472,40.129398,-75.332213,PINE ST & W ROBERTS ST; NORRISTOWN; Station 3...,19401.0,EMS: CARDIAC EMERGENCY,2016-08-24 10:22:00,NORRISTOWN,PINE ST & W ROBERTS ST,1,EMS,10,8,2
99473,40.133533,-75.056460,BUCK RD & WAVERLY LN; BRYN ATHYN; Station 355...,19009.0,EMS: GENERAL WEAKNESS,2016-08-24 10:27:01,BRYN ATHYN,BUCK RD & WAVERLY LN,1,EMS,10,8,2
99474,40.078678,-75.086943,HUNTINGDON PIKE & FILLMORE ST; ROCKLEDGE; Sta...,19046.0,EMS: SEIZURES,2016-08-24 10:27:01,ROCKLEDGE,HUNTINGDON PIKE & FILLMORE ST,1,EMS,10,8,2
99475,40.133715,-75.229630,SHEAFF LN & WHITEMARSH VALLEY RD; WHITEMARSH; ...,19034.0,Traffic: VEHICLE ACCIDENT -,2016-08-24 10:32:01,WHITEMARSH,SHEAFF LN & WHITEMARSH VALLEY RD,1,Traffic,10,8,2
99476,40.257820,-75.624294,PARK DR & N ADAMS ST; POTTSTOWN; Station 329;...,19464.0,EMS: RESPIRATORY EMERGENCY,2016-08-24 10:47:00,POTTSTOWN,PARK DR & N ADAMS ST,1,EMS,10,8,2
99477,40.095652,-75.244877,FOX HOUND DR & MARBLE HL; WHITEMARSH; Station...,19444.0,EMS: SUBJECT IN PAIN,2016-08-24 10:47:00,WHITEMARSH,FOX HOUND DR & MARBLE HL,1,EMS,10,8,2
99478,40.100344,-75.293955,CHEMICAL RD & GALLAGHER RD; PLYMOUTH; 2016-08-...,19462.0,Traffic: VEHICLE ACCIDENT -,2016-08-24 10:47:02,PLYMOUTH,CHEMICAL RD & GALLAGHER RD,1,Traffic,10,8,2
99479,40.221227,-75.288737,SUMNEYTOWN PIKE & RR OVERPASS; UPPER GWYNEDD;...,NaN,EMS: CARDIAC EMERGENCY,2016-08-24 10:52:01,UPPER GWYNEDD,SUMNEYTOWN PIKE & RR OVERPASS,1,EMS,10,8,2
99480,40.221227,-75.288737,SUMNEYTOWN PIKE & RR OVERPASS; UPPER GWYNEDD;...,NaN,EMS: DIABETIC EMERGENCY,2016-08-24 10:52:01,UPPER GWYNEDD,SUMNEYTOWN PIKE & RR OVERPASS,1,EMS,10,8,2
99481,40.221227,-75.288737,SUMNEYTOWN PIKE & RR OVERPASS; UPPER GWYNEDD;...,NaN,EMS: DIZZINESS,2016-08-24 10:52:01,UPPER GWYNEDD,SUMNEYTOWN PIKE & RR OVERPASS,1,EMS,10,8,2
99482,40.340072,-75.591709,RT100 SB & E PHILADELPHIA AVE OVERPASS; DOUGLA...,NaN,Traffic: DISABLED VEHICLE -,2016-08-24 10:52:03,DOUGLASS,RT100 SB & E PHILADELPHIA AVE OVERPASS,1,Traffic,10,8,2
99483,40.084465,-75.390173,DEKALB PIKE & KING OF PRUSSIA RD; UPPER MERIO...,19406.0,EMS: BACK PAINS/INJURY,2016-08-24 10:57:00,UPPER MERION,DEKALB PIKE & KING OF PRUSSIA RD,1,EMS,10,8,2
99484,40.133037,-75.408463,SHANNONDELL DR & SHANNONDELL BLVD; LOWER PROVI...,19403.0,Fire: FIRE ALARM,2016-08-24 10:57:00,LOWER PROVIDENCE,SHANNONDELL DR & SHANNONDELL BLVD,1,Fire,10,8,2
99485,40.143601,-75.427877,EAGLEVILLE RD & REDTAIL RD; LOWER PROVIDENCE; ...,19403.0,Traffic: DISABLED VEHICLE -,2016-08-24 10:57:01,LOWER PROVIDENCE,EAGLEVILLE RD & REDTAIL RD,1,Traffic,10,8,2
99486,40.179225,-75.180572,WELSH RD & NORRISTOWN RD; HORSHAM; 2016-08-24 ...,19044.0,Traffic: VEHICLE ACCIDENT -,2016-08-24 11:02:02,HORSHAM,WELSH RD & NORRISTOWN RD,1,Traffic,11,8,2
99487,40.132869,-75.333515,MARKLEY ST & W LOGAN ST; NORRISTOWN; 2016-08-2...,19401.0,Traffic: VEHICLE ACCIDENT -,2016-08-24 11:06:00,NORRISTOWN,MARKLEY ST & W LOGAN ST,1,Traffic,11,8,2
99488,40.006974,-75.289080,LANCASTER AVE & RITTENHOUSE PL; LOWER MERION; ...,19003.0,Traffic: VEHICLE ACCIDENT -,2016-08-24 11:07:02,LOWER MERION,LANCASTER AVE & RITTENHOUSE PL,1,Traffic,11,8,2
99489,40.115429,-75.334679,CHESTNUT ST & WALNUT ST; NORRISTOWN; Station ...,19401.0,EMS: FALL VICTIM,2016-08-24 11:12:00,NORRISTOWN,CHESTNUT ST & WALNUT ST,1,EMS,11,8,2
99490,40.186431,-75.192555,WELSH RD & WEBSTER LN; HORSHAM; Station 352; ...,19002.0,EMS: NAUSEA/VOMITING,2016-08-24 11:17:01,HORSHAM,WELSH RD & WEBSTER LN,1,EMS,11,8,2
99491,40.207055,-75.317952,MORRIS RD & S BROAD ST; UPPER GWYNEDD; 2016-08...,19446.0,Traffic: VEHICLE ACCIDENT -,2016-08-24 11:17:02,UPPER GWYNEDD,MORRIS RD & S BROAD ST,1,Traffic,11,8,2

### Observe como o dia da demana é um número inteiro de 0-6. Mapeie os nomes das seqüências reais para o dia da semana, nessa mesma coluna:

- 0 => Mon
- 1 => Tue
- 2 => Wed
- 3 => Thu
- 4 => Fri
- 5 => Sat
- 6 => Sun

### -_Conversão dos dias da semana de número para nome do dia_

In [49]:
calls['Day_of_Week'] = calls.timeStamp.dt.strftime('%a')
calls

,lat,lng,desc,zip,title,timeStamp,twp,addr,e,Reason,Hour,Month,Day_of_Week
0,40.297876,-75.581294,REINDEER CT & DEAD END; NEW HANOVER; Station ...,19525.0,EMS: BACK PAINS/INJURY,2015-12-10 17:40:00,NEW HANOVER,REINDEER CT & DEAD END,1,EMS,17,12,Thu
1,40.258061,-75.264680,BRIAR PATH & WHITEMARSH LN; HATFIELD TOWNSHIP...,19446.0,EMS: DIABETIC EMERGENCY,2015-12-10 17:40:00,HATFIELD TOWNSHIP,BRIAR PATH & WHITEMARSH LN,1,EMS,17,12,Thu
2,40.121182,-75.351975,HAWS AVE; NORRISTOWN; 2015-12-10 @ 14:39:21-St...,19401.0,Fire: GAS-ODOR/LEAK,2015-12-10 17:40:00,NORRISTOWN,HAWS AVE,1,Fire,17,12,Thu
3,40.116153,-75.343513,AIRY ST & SWEDE ST; NORRISTOWN; Station 308A;...,19401.0,EMS: CARDIAC EMERGENCY,2015-12-10 17:40:01,NORRISTOWN,AIRY ST & SWEDE ST,1,EMS,17,12,Thu
4,40.251492,-75.603350,CHERRYWOOD CT & DEAD END; LOWER POTTSGROVE; S...,NaN,EMS: DIZZINESS,2015-12-10 17:40:01,LOWER POTTSGROVE,CHERRYWOOD CT & DEAD END,1,EMS,17,12,Thu
5,40.253473,-75.283245,CANNON AVE & W 9TH ST; LANSDALE; Station 345;...,19446.0,EMS: HEAD INJURY,2015-12-10 17:40:01,LANSDALE,CANNON AVE & W 9TH ST,1,EMS,17,12,Thu
6,40.182111,-75.127795,LAUREL AVE & OAKDALE AVE; HORSHAM; Station 35...,19044.0,EMS: NAUSEA/VOMITING,2015-12-10 17:40:01,HORSHAM,LAUREL AVE & OAKDALE AVE,1,EMS,17,12,Thu
7,40.217286,-75.405182,COLLEGEVILLE RD & LYWISKI RD; SKIPPACK; Stati...,19426.0,EMS: RESPIRATORY EMERGENCY,2015-12-10 17:40:01,SKIPPACK,COLLEGEVILLE RD & LYWISKI RD,1,EMS,17,12,Thu
8,40.289027,-75.399590,MAIN ST & OLD SUMNEYTOWN PIKE; LOWER SALFORD;...,19438.0,EMS: SYNCOPAL EPISODE,2015-12-10 17:40:01,LOWER SALFORD,MAIN ST & OLD SUMNEYTOWN PIKE,1,EMS,17,12,Thu
9,40.102398,-75.291458,BLUEROUTE & RAMP I476 NB TO CHEMICAL RD; PLYM...,19462.0,Traffic: VEHICLE ACCIDENT -,2015-12-10 17:40:01,PLYMOUTH,BLUEROUTE & RAMP I476 NB TO CHEMICAL RD,1,Traffic,17,12,Thu
10,40.231990,-75.251891,RT202 PKWY & KNAPP RD; MONTGOMERY; 2015-12-10 ...,NaN,Traffic: VEHICLE ACCIDENT -,2015-12-10 17:40:01,MONTGOMERY,RT202 PKWY & KNAPP RD,1,Traffic,17,12,Thu
11,40.084161,-75.308386,BROOK RD & COLWELL LN; PLYMOUTH; 2015-12-10 @ ...,19428.0,Traffic: VEHICLE ACCIDENT -,2015-12-10 17:40:02,PLYMOUTH,BROOK RD & COLWELL LN,1,Traffic,17,12,Thu
12,40.174131,-75.098491,BYBERRY AVE & S WARMINSTER RD; UPPER MORELAND;...,19040.0,Traffic: VEHICLE ACCIDENT -,2015-12-10 17:40:02,UPPER MORELAND,BYBERRY AVE & S WARMINSTER RD,1,Traffic,17,12,Thu
13,40.062974,-75.135914,OLD YORK RD & VALLEY RD; CHELTENHAM; 2015-12-1...,19027.0,Traffic: VEHICLE ACCIDENT -,2015-12-10 17:40:02,CHELTENHAM,OLD YORK RD & VALLEY RD,1,Traffic,17,12,Thu
14,40.097222,-75.376195,SCHUYLKILL EXPY & CROTON RD UNDERPASS; UPPER M...,NaN,Traffic: VEHICLE ACCIDENT -,2015-12-10 17:40:02,UPPER MERION,SCHUYLKILL EXPY & CROTON RD UNDERPASS,1,Traffic,17,12,Thu
15,40.223778,-75.235399,STUMP RD & WITCHWOOD DR; MONTGOMERY; 2015-12-1...,18936.0,Traffic: VEHICLE ACCIDENT -,2015-12-10 17:40:02,MONTGOMERY,STUMP RD & WITCHWOOD DR,1,Traffic,17,12,Thu
16,40.243258,-75.286552,SUSQUEHANNA AVE & W MAIN ST; LANSDALE; Statio...,19446.0,EMS: RESPIRATORY EMERGENCY,2015-12-10 17:46:01,LANSDALE,SUSQUEHANNA AVE & W MAIN ST,1,EMS,17,12,Thu
17,40.312181,-75.574260,CHARLOTTE ST & MILES RD; NEW HANOVER; Station...,19525.0,EMS: DIZZINESS,2015-12-10 17:47:01,NEW HANOVER,CHARLOTTE ST & MILES RD,1,EMS,17,12,Thu
18,40.114239,-75.338508,PENN ST & ARCH ST; NORRISTOWN; Station 308A; ...,19401.0,EMS: VEHICLE ACCIDENT,2015-12-10 17:47:01,NORRISTOWN,PENN ST & ARCH ST,1,EMS,17,12,Thu
19,40.209337,-75.135266,COUNTY LINE RD & WILLOW DR; HORSHAM; 2015-12-1...,18974.0,Traffic: DISABLED VEHICLE -,2015-12-10 17:47:02,HORSHAM,COUNTY LINE RD & WILLOW DR,1,Traffic,17,12,Thu
20,40.114239,-75.338508,PENN ST & ARCH ST; NORRISTOWN; 2015-12-10 @ 17...,19401.0,Traffic: VEHICLE ACCIDENT -,2015-12-10 17:47:02,NORRISTOWN,PENN ST & ARCH ST,1,Traffic,17,12,Thu
21,40.117948,-75.209848,CHURCH RD & REDCOAT DR; WHITEMARSH; 2015-12-10...,19031.0,Traffic: DISABLED VEHICLE -,2015-12-10 17:57:02,WHITEMARSH,CHURCH RD & REDCOAT DR,1,Traffic,17,12,Thu
22,40.199006,-75.300058,LILAC CT & PRIMROSE DR; UPPER GWYNEDD; 2015-12...,19446.0,Fire: APPLIANCE FIRE,2015-12-10 18:02:01,UPPER GWYNEDD,LILAC CT & PRIMROSE DR,1,Fire,18,12,Thu
23,40.143326,-75.422819,RT422 & PAWLINGS RD OVERPASS; LOWER PROVIDENC...,NaN,Traffic: DISABLED VEHICLE -,2015-12-10 18:02:02,LOWER PROVIDENCE,RT422 & PAWLINGS RD OVERPASS,1,Traffic,18,12,Thu
24,40.153268,-75.189558,SUMMIT AVE & RT309 UNDERPASS; UPPER DUBLIN; 20...,NaN,Traffic: VEHICLE ACCIDENT -,2015-12-10 18:02:02,UPPER DUBLIN,SUMMIT AVE & RT309 UNDERPASS,1,Traffic,18,12,Thu
25,40.133037,-75.408463,SHANNONDELL DR & SHANNONDELL BLVD; LOWER PROV...,19403.0,EMS: GENERAL WEAKNESS,2015-12-10 18:06:25,LOWER PROVIDENCE,SHANNONDELL DR & SHANNONDELL BLVD,1,EMS,18,12,Thu
26,40.155283,-75.264230,PENLLYN BLUE BELL PIKE & VILLAGE CIR; WHITPAI...,19422.0,EMS: HEAD INJURY,2015-12-10 18:06:25,WHITPAIN,PENLLYN BLUE BELL PIKE & VILLAGE CIR,1,EMS,18,12,Thu
27,40.028903,-75.351822,EDENTON PL & DURHAM DR; DELAWARE COUNTY; 2015-...,19085.0,Fire: CARBON MONOXIDE DETECTOR,2015-12-10 18:06:25,DELAWARE COUNTY,EDENTON PL & DURHAM DR,1,Fire,18,12,Thu
28,40.097222,-75.376195,SCHUYLKILL EXPY & WEADLEY RD OVERPASS; UPPER M...,NaN,Traffic: VEHICLE ACCIDENT -,2015-12-10 18:06:26,UPPER MERION,SCHUYLKILL EXPY & WEADLEY RD OVERPASS,1,Traffic,18,12,Thu
29,40.209337,-75.135266,COUNTY LINE RD & WILLOW DR; HORSHAM; 2015-12-1...,18974.0,Traffic: DISABLED VEHICLE -,2015-12-10 18:11:01,HORSHAM,COUNTY LINE RD & WILLOW DR,1,Traffic,18,12,Thu
...,...,...,...,...,...,...,...,...,...,...,...,...,...
99462,40.274137,-75.660469,UPLAND SQUARE DR & SELL RD; WEST POTTSGROVE; ...,19464.0,EMS: UNKNOWN MEDICAL EMERGENCY,2016-08-24 09:41:00,WEST POTTSGROVE,UPLAND SQUARE DR & SELL RD,1,EMS,9,8,Wed
99463,40.254768,-75.660459,SHOEMAKER RD & ROBINSON ST; POTTSTOWN; Statio...,19464.0,EMS: UNKNOWN MEDICAL EMERGENCY,2016-08-24 09:42:00,POTTSTOWN,SHOEMAKER RD & ROBINSON ST,1,EMS,9,8,Wed
99464,40.163730,-75.082753,KAREN LN & BYBERRY RD; UPPER MORELAND; Statio...,19040.0,EMS: FALL VICTIM,2016-08-24 09:51:06,UPPER MORELAND,KAREN LN & BYBERRY RD,1,EMS,9,8,Wed
99465,40.114928,-75.340307,AIRY ST & GREEN ST; NORRISTOWN; Station 308A;...,19401.0,EMS: RESPIRATORY EMERGENCY,2016-08-24 09:56:13,NORRISTOWN,AIRY ST & GREEN ST,1,EMS,9,8,Wed
99466,40.159820,-75.288436,WENTZ RD & SILO CIR; WHITPAIN; Station 385; 2...,19422.0,EMS: NAUSEA/VOMITING,2016-08-24 10:01:00,WHITPAIN,WENTZ RD & SILO CIR,1,EMS,10,8,Wed
99467,40.255271,-75.340722,WOODS DR & DETWILER RD; TOWAMENCIN; Station 3...,19446.0,EMS: ALTERED MENTAL STATUS,2016-08-24 10:12:01,TOWAMENCIN,WOODS DR & DETWILER RD,1,EMS,10,8,Wed
99468,40.088355,-75.382100,DEKALB PIKE & ALLENDALE RD; UPPER MERION; 2016...,19406.0,Fire: FIRE ALARM,2016-08-24 10:12:01,UPPER MERION,DEKALB PIKE & ALLENDALE RD,1,Fire,10,8,Wed
99469,40.123868,-75.341678,MARKLEY ST & JAMES ST; NORRISTOWN; 2016-08-24 ...,19401.0,Fire: FIRE ALARM,2016-08-24 10:12:01,NORRISTOWN,MARKLEY ST & JAMES ST,1,Fire,10,8,Wed
99470,40.185798,-75.536484,WALNUT ST & S 5TH AVE; ROYERSFORD; Station 32...,19468.0,EMS: ALTERED MENTAL STATUS,2016-08-24 10:17:01,ROYERSFORD,WALNUT ST & S 5TH AVE,1,EMS,10,8,Wed
99471,40.000763,-75.279769,WYNNEWOOD RD & W OLD WYNNEWOOD RD; LOWER MERI...,19096.0,EMS: RESPIRATORY EMERGENCY,2016-08-24 10:17:01,LOWER MERION,WYNNEWOOD RD & W OLD WYNNEWOOD RD,1,EMS,10,8,Wed
99472,40.129398,-75.332213,PINE ST & W ROBERTS ST; NORRISTOWN; Station 3...,19401.0,EMS: CARDIAC EMERGENCY,2016-08-24 10:22:00,NORRISTOWN,PINE ST & W ROBERTS ST,1,EMS,10,8,Wed
99473,40.133533,-75.056460,BUCK RD & WAVERLY LN; BRYN ATHYN; Station 355...,19009.0,EMS: GENERAL WEAKNESS,2016-08-24 10:27:01,BRYN ATHYN,BUCK RD & WAVERLY LN,1,EMS,10,8,Wed
99474,40.078678,-75.086943,HUNTINGDON PIKE & FILLMORE ST; ROCKLEDGE; Sta...,19046.0,EMS: SEIZURES,2016-08-24 10:27:01,ROCKLEDGE,HUNTINGDON PIKE & FILLMORE ST,1,EMS,10,8,Wed
99475,40.133715,-75.229630,SHEAFF LN & WHITEMARSH VALLEY RD; WHITEMARSH; ...,19034.0,Traffic: VEHICLE ACCIDENT -,2016-08-24 10:32:01,WHITEMARSH,SHEAFF LN & WHITEMARSH VALLEY RD,1,Traffic,10,8,Wed
99476,40.257820,-75.624294,PARK DR & N ADAMS ST; POTTSTOWN; Station 329;...,19464.0,EMS: RESPIRATORY EMERGENCY,2016-08-24 10:47:00,POTTSTOWN,PARK DR & N ADAMS ST,1,EMS,10,8,Wed
99477,40.095652,-75.244877,FOX HOUND DR & MARBLE HL; WHITEMARSH; Station...,19444.0,EMS: SUBJECT IN PAIN,2016-08-24 10:47:00,WHITEMARSH,FOX HOUND DR & MARBLE HL,1,EMS,10,8,Wed
99478,40.100344,-75.293955,CHEMICAL RD & GALLAGHER RD; PLYMOUTH; 2016-08-...,19462.0,Traffic: VEHICLE ACCIDENT -,2016-08-24 10:47:02,PLYMOUTH,CHEMICAL RD & GALLAGHER RD,1,Traffic,10,8,Wed
99479,40.221227,-75.288737,SUMNEYTOWN PIKE & RR OVERPASS; UPPER GWYNEDD;...,NaN,EMS: CARDIAC EMERGENCY,2016-08-24 10:52:01,UPPER GWYNEDD,SUMNEYTOWN PIKE & RR OVERPASS,1,EMS,10,8,Wed
99480,40.221227,-75.288737,SUMNEYTOWN PIKE & RR OVERPASS; UPPER GWYNEDD;...,NaN,EMS: DIABETIC EMERGENCY,2016-08-24 10:52:01,UPPER GWYNEDD,SUMNEYTOWN PIKE & RR OVERPASS,1,EMS,10,8,Wed
99481,40.221227,-75.288737,SUMNEYTOWN PIKE & RR OVERPASS; UPPER GWYNEDD;...,NaN,EMS: DIZZINESS,2016-08-24 10:52:01,UPPER GWYNEDD,SUMNEYTOWN PIKE & RR OVERPASS,1,EMS,10,8,Wed
99482,40.340072,-75.591709,RT100 SB & E PHILADELPHIA AVE OVERPASS; DOUGLA...,NaN,Traffic: DISABLED VEHICLE -,2016-08-24 10:52:03,DOUGLASS,RT100 SB & E PHILADELPHIA AVE OVERPASS,1,Traffic,10,8,Wed
99483,40.084465,-75.390173,DEKALB PIKE & KING OF PRUSSIA RD; UPPER MERIO...,19406.0,EMS: BACK PAINS/INJURY,2016-08-24 10:57:00,UPPER MERION,DEKALB PIKE & KING OF PRUSSIA RD,1,EMS,10,8,Wed
99484,40.133037,-75.408463,SHANNONDELL DR & SHANNONDELL BLVD; LOWER PROVI...,19403.0,Fire: FIRE ALARM,2016-08-24 10:57:00,LOWER PROVIDENCE,SHANNONDELL DR & SHANNONDELL BLVD,1,Fire,10,8,Wed
99485,40.143601,-75.427877,EAGLEVILLE RD & REDTAIL RD; LOWER PROVIDENCE; ...,19403.0,Traffic: DISABLED VEHICLE -,2016-08-24 10:57:01,LOWER PROVIDENCE,EAGLEVILLE RD & REDTAIL RD,1,Traffic,10,8,Wed
99486,40.179225,-75.180572,WELSH RD & NORRISTOWN RD; HORSHAM; 2016-08-24 ...,19044.0,Traffic: VEHICLE ACCIDENT -,2016-08-24 11:02:02,HORSHAM,WELSH RD & NORRISTOWN RD,1,Traffic,11,8,Wed
99487,40.132869,-75.333515,MARKLEY ST & W LOGAN ST; NORRISTOWN; 2016-08-2...,19401.0,Traffic: VEHICLE ACCIDENT -,2016-08-24 11:06:00,NORRISTOWN,MARKLEY ST & W LOGAN ST,1,Traffic,11,8,Wed
99488,40.006974,-75.289080,LANCASTER AVE & RITTENHOUSE PL; LOWER MERION; ...,19003.0,Traffic: VEHICLE ACCIDENT -,2016-08-24 11:07:02,LOWER MERION,LANCASTER AVE & RITTENHOUSE PL,1,Traffic,11,8,Wed
99489,40.115429,-75.334679,CHESTNUT ST & WALNUT ST; NORRISTOWN; Station ...,19401.0,EMS: FALL VICTIM,2016-08-24 11:12:00,NORRISTOWN,CHESTNUT ST & WALNUT ST,1,EMS,11,8,Wed
99490,40.186431,-75.192555,WELSH RD & WEBSTER LN; HORSHAM; Station 352; ...,19002.0,EMS: NAUSEA/VOMITING,2016-08-24 11:17:01,HORSHAM,WELSH RD & WEBSTER LN,1,EMS,11,8,Wed
99491,40.207055,-75.317952,MORRIS RD & S BROAD ST; UPPER GWYNEDD; 2016-08...,19446.0,Traffic: VEHICLE ACCIDENT -,2016-08-24 11:17:02,UPPER GWYNEDD,MORRIS RD & S BROAD ST,1,Traffic,11,8,Wed

### Qual a quantidade de chamadas de cada motivo (_Reason_) por mês?

### -_Agrupar chamados por motivo e por mês_

In [50]:
calls.groupby(['Reason','Month']).size()

Reason   Month
EMS      1        6063
         2        5413
         3        5832
         4        5680
         5        5734
         6        5720
         7        6029
         8        4508
         12       3898
Fire     1        1905
         2        1869
         3        1590
         4        1717
         5        1573
         6        1796
         7        1901
         8        1473
         12       1096
Traffic  1        5237
         2        4185
         3        3679
         4        3929
         5        4116
         6        4270
         7        4207
         8        3097
         12       2975
dtype: int64

### Qual foi o dia com a maior quantidade de chamadas? Quantas chamadas foram executadas neste dia?

### -_Mostrar o dia com mais chamados e quantidade de chamados neste dia_

In [51]:
calls.timeStamp.dt.strftime('%Y-%m-%d').value_counts().nlargest(1)

2016-01-23    913
Name: timeStamp, dtype: int64

### Levando-se em consideração apenas atendimentos feitos às sextas-feiras, qual a hora do dia com o maior número de chamadas?

### -_Mostrar a hora com mais chamados nas sextas-feiras_

In [52]:
calls[calls.Day_of_Week=='Fri'].Hour.value_counts().nlargest(1)

16    1039
Name: Hour, dtype: int64

### Levando-se em consideração os atendimentos relacionados a incêndio (_Reason_ = _Fire_) qual a quantidade de chamados aos sábados?

### -_Mostrar a quantidade de chamados de incêndio aos sábados_

In [53]:
calls[(calls.Reason=='Fire') & (calls.Day_of_Week=='Sat')].Day_of_Week.value_counts().nlargest(1)

Sat    2068
Name: Day_of_Week, dtype: int64