In [11]:
import pandas as pd
import numpy as np

In [3]:
desired_width = 320
np.set_printoptions(linewidth=desired_width)
pd.set_option('display.width', desired_width)
pd.set_option('display.max_columns',20)
pd.set_option('display.max_rows', None)

In [4]:
dt = pd.read_json("dataset_monitoramento_fauna.json")
dt.head()

   id_registro id_camera     data_hora_inicio  duracao_segundos            especie     grupo  individuos temperatura_c umidade_pct
0            1     CAM01  2026-05-01 00:04:00                25                Ema       Ave           3       19.3 °C       81.5%
1            2     CAM08  2026-05-01 00:18:00                 9        Rã-manteiga   Anfíbio           3       16.6 °C       88.8%
2            3     CAM08  2026-05-01 00:32:00                 6      Tatu-canastra  Mamífero           1       16.5 °C       96.3%
3            4     CAM12  2026-05-01 00:37:00                13        Rã-manteiga   Anfíbio           2       19.2 °C       92.1%
4            5     CAM03  2026-05-01 00:39:00                25  Tamanduá-bandeira  Mamífero           1       20.5 °C       82.6%

In [18]:
dt.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id_registro       5000 non-null   int64
 1   id_camera         5000 non-null   str
 2   data_hora_inicio  5000 non-null   str
 3   duracao_segundos  5000 non-null   int64
 4   especie           5000 non-null   str
 5   grupo             5000 non-null   str
 6   individuos        5000 non-null   int64
 7   temperatura_c     4753 non-null   str
 8   umidade_pct       4825 non-null   str
dtypes: int64(3), str(6)
memory usage: 351.7 KB

In [19]:
pd.concat([dt.head(10),dt.iloc[-8:]])

      id_registro id_camera     data_hora_inicio  duracao_segundos            especie     grupo  individuos temperatura_c umidade_pct
0               1     CAM01  2026-05-01 00:04:00                25                Ema       Ave           3       19.3 °C       81.5%
1               2     CAM08  2026-05-01 00:18:00                 9        Rã-manteiga   Anfíbio           3       16.6 °C       88.8%
2               3     CAM08  2026-05-01 00:32:00                 6      Tatu-canastra  Mamífero           1       16.5 °C       96.3%
3               4     CAM12  2026-05-01 00:37:00                13        Rã-manteiga   Anfíbio           2       19.2 °C       92.1%
4               5     CAM03  2026-05-01 00:39:00                25  Tamanduá-bandeira  Mamífero           1       20.5 °C       82.6%
5               6     CAM08  2026-05-01 00:47:00                19        Sapo-cururu   Anfíbio           3       18.2 °C       90.9%
6               7     CAM12  2026-05-01 00:48:00                46              Quati  Mamífero           4       16.9 °C       95.5%
7               8     CAM05  2026-05-01 00:49:00                35     Perereca-verde   Anfíbio           2       14.6 °C       94.1%
8               9     CAM04  2026-05-01 00:49:00                46        Sapo-cururu   Anfíbio           3       20.6 °C       92.8%
9              10     CAM12  2026-05-01 00:51:00                31           Capivara  Mamífero           6       20.8 °C       97.1%
4992         4993     CAM09  2026-05-30 22:03:00                11     Perereca-verde   Anfíbio           4       18.3 °C       87.7%
4993         4994     CAM05  2026-05-30 22:17:00                85        Sapo-cururu   Anfíbio           2       20.3 °C       83.6%
4994         4995     CAM06  2026-05-30 22:22:00                 6        Rã-manteiga   Anfíbio           1       19.5 °C       91.0%
4995         4996     CAM08  2026-05-30 22:50:00                11           Capivara  Mamífero           8       19.7 °C       89.5%
4996         4997     CAM11  2026-05-30 23:00:00                53     Perereca-verde   Anfíbio           1           NaN         NaN
4997         4998     CAM07  2026-05-30 23:19:00                51         Lobo-guará  Mamífero           1       19.8 °C         NaN
4998         4999     CAM06  2026-05-30 23:25:00                33        Sapo-cururu   Anfíbio           2       18.2 °C       83.6%
4999         5000     CAM12  2026-05-30 23:58:00                64              Quati  Mamífero           2       17.9 °C       96.7%

In [20]:
nan = dt.isnull().any()
nan

id_registro         False
id_camera           False
data_hora_inicio    False
duracao_segundos    False
especie             False
grupo               False
individuos          False
temperatura_c        True
umidade_pct          True
dtype: bool

In [21]:
where = dt.columns[nan] 
where

Index(['temperatura_c', 'umidade_pct'], dtype='str')

In [22]:
dt[where].isnull().sum()

temperatura_c    247
umidade_pct      175
dtype: int64

In [23]:
dt.especie.value_counts()

especie
Capivara             731
Sapo-cururu          564
Ema                  551
Seriema              506
Lobo-guará           425
Tamanduá-bandeira    401
Perereca-verde       389
Quati                378
Rã-manteiga          317
Veado-campeiro       292
Tatu-canastra        273
Cervo-do-pantanal    153
Onça-pintada          20
Name: count, dtype: int64

In [24]:
dt.especie.unique()

<StringArray>
['Ema', 'Rã-manteiga', 'Tatu-canastra', 'Tamanduá-bandeira', 'Sapo-cururu', 'Quati', 'Perereca-verde', 'Capivara', 'Veado-campeiro', 'Lobo-guará', 'Seriema', 'Onça-pintada', 'Cervo-do-pantanal']
Length: 13, dtype: str

In [25]:
dt.id_camera.value_counts()

id_camera
CAM09    523
CAM12    504
CAM10    474
CAM02    471
CAM04    442
CAM08    418
CAM06    400
CAM01    394
CAM05    377
CAM07    364
CAM03    317
CAM11    316
Name: count, dtype: int64

In [26]:
dt[["id_camera","especie"]].groupby("especie").count()

                   id_camera
especie
Capivara                 731
Cervo-do-pantanal        153
Ema                      551
Lobo-guará               425
Onça-pintada              20
Perereca-verde           389
Quati                    378
Rã-manteiga              317
Sapo-cururu              564
Seriema                  506
Tamanduá-bandeira        401
Tatu-canastra            273
Veado-campeiro           292

In [27]:
resultado = (
    dt.value_counts(["id_camera", "especie"])
    .reset_index(name="count")
    .sort_values(
        by=["id_camera", "count"],
        ascending=[True, False]
    )
)

resultado

    id_camera            especie  count
8       CAM01                Ema     80
10      CAM01            Seriema     76
18      CAM01         Lobo-guará     66
33      CAM01     Veado-campeiro     53
54      CAM01  Tamanduá-bandeira     35
62      CAM01      Tatu-canastra     32
101     CAM01        Sapo-cururu     14
103     CAM01              Quati     14
125     CAM01           Capivara      9
129     CAM01  Cervo-do-pantanal      7
134     CAM01     Perereca-verde      6
143     CAM01        Rã-manteiga      2
3       CAM02                Ema    100
4       CAM02            Seriema     94
14      CAM02         Lobo-guará     71
22      CAM02  Tamanduá-bandeira     61
27      CAM02     Veado-campeiro     56
67      CAM02      Tatu-canastra     30
97      CAM02        Sapo-cururu     17
98      CAM02              Quati     17
120     CAM02           Capivara     11
131     CAM02        Rã-manteiga      6
133     CAM02     Perereca-verde      6
147     CAM02  Cervo-do-pantanal      2
16      CAM03                Ema     68
21      CAM03            Seriema     62
45      CAM03         Lobo-guará     45
59      CAM03  Tamanduá-bandeira     33
60      CAM03     Veado-campeiro     33
78      CAM03      Tatu-canastra     27
87      CAM03        Sapo-cururu     21
121     CAM03              Quati     10
130     CAM03  Cervo-do-pantanal      7
136     CAM03           Capivara      5
141     CAM03     Perereca-verde      3
142     CAM03        Rã-manteiga      3
5       CAM04            Seriema     90
13      CAM04                Ema     72
15      CAM04         Lobo-guará     71
17      CAM04     Veado-campeiro     68
35      CAM04  Tamanduá-bandeira     49
69      CAM04      Tatu-canastra     30
88      CAM04        Sapo-cururu     20
99      CAM04              Quati     16
112     CAM04           Capivara     12
122     CAM04     Perereca-verde     10
144     CAM04  Cervo-do-pantanal      2
148     CAM04        Rã-manteiga      2
23      CAM05           Capivara     59
34      CAM05              Quati     52
42      CAM05        Sapo-cururu     45
51      CAM05  Tamanduá-bandeira     37
52      CAM05        Rã-manteiga     37
58      CAM05     Perereca-verde     34
65      CAM05      Tatu-canastra     31
68      CAM05            Seriema     30
91      CAM05                Ema     18
102     CAM05         Lobo-guará     14
123     CAM05  Cervo-do-pantanal      9
124     CAM05     Veado-campeiro      9
146     CAM05       Onça-pintada      2
25      CAM06              Quati     59
28      CAM06           Capivara     56
37      CAM06        Sapo-cururu     48
38      CAM06  Tamanduá-bandeira     48
48      CAM06     Perereca-verde     40
50      CAM06        Rã-manteiga     38
70      CAM06      Tatu-canastra     30
80      CAM06            Seriema     26
107     CAM06     Veado-campeiro     13
109     CAM06         Lobo-guará     13
113     CAM06                Ema     12
118     CAM06  Cervo-do-pantanal     11
132     CAM06       Onça-pintada      6
29      CAM07              Quati     55
36      CAM07        Sapo-cururu     48
44      CAM07           Capivara     45
47      CAM07  Tamanduá-bandeira     41
56      CAM07      Tatu-canastra     35
61      CAM07        Rã-manteiga     32
75      CAM07     Perereca-verde     28
79      CAM07            Seriema     26
93      CAM07         Lobo-guará     17
114     CAM07     Veado-campeiro     11
117     CAM07  Cervo-do-pantanal     11
119     CAM07                Ema     11
140     CAM07       Onça-pintada      4
19      CAM08              Quati     65
26      CAM08           Capivara     58
39      CAM08        Sapo-cururu     46
43      CAM08     Perereca-verde     45
53      CAM08  Tamanduá-bandeira     36
63      CAM08            Seriema     32
71      CAM08        Rã-manteiga     29
74      CAM08         Lobo-guará     28
76      CAM08      Tatu-canastra     27
95      CAM08  Cervo-do-pantanal     17
96      CAM08     Veado-campeiro     17
111     CAM08                Ema     13
139     CAM08       Onça-pintada      5
0       CAM09           Capivara    141
6       CAM09        Sapo-cururu     88
11      CAM09     Perereca-verde     74
31      CAM09        Rã-manteiga     53
32      CAM09                Ema     53
66      CAM09         Lobo-guará     30
82      CAM09              Quati     22
90      CAM09            Seriema     19
100     CAM09  Cervo-do-pantanal     16
115     CAM09  Tamanduá-bandeira     11
126     CAM09     Veado-campeiro      8
127     CAM09      Tatu-canastra      8
1       CAM10           Capivara    137
9       CAM10        Sapo-cururu     77
20      CAM10     Perereca-verde     62
46      CAM10        Rã-manteiga     43
49      CAM10                Ema     39
72      CAM10         Lobo-guará     29
81      CAM10  Cervo-do-pantanal     25
85      CAM10              Quati     21
92      CAM10            Seriema     17
104     CAM10  Tamanduá-bandeira     14
137     CAM10      Tatu-canastra      5
138     CAM10     Veado-campeiro      5
12      CAM11           Capivara     73
24      CAM11        Sapo-cururu     59
55      CAM11     Perereca-verde     35
64      CAM11                Ema     32
77      CAM11        Rã-manteiga     27
89      CAM11         Lobo-guará     20
94      CAM11  Cervo-do-pantanal     17
106     CAM11  Tamanduá-bandeira     14
108     CAM11            Seriema     13
110     CAM11              Quati     13
128     CAM11      Tatu-canastra      7
135     CAM11     Veado-campeiro      5
149     CAM11       Onça-pintada      1
2       CAM12           Capivara    125
7       CAM12        Sapo-cururu     81
30      CAM12                Ema     53
40      CAM12     Perereca-verde     46
41      CAM12        Rã-manteiga     45
57      CAM12              Quati     34
73      CAM12  Cervo-do-pantanal     29
83      CAM12  Tamanduá-bandeira     22
84      CAM12         Lobo-guará     21
86      CAM12            Seriema     21
105     CAM12     Veado-campeiro     14
116     CAM12      Tatu-canastra     11
145     CAM12       Onça-pintada      2

In [31]:
capi = dt[(dt.especie=='Capivara')]
capi.head(10)

    id_registro id_camera     data_hora_inicio  duracao_segundos   especie     grupo  individuos temperatura_c umidade_pct
9            10     CAM12  2026-05-01 00:51:00                31  Capivara  Mamífero           6       20.8 °C       97.1%
22           23     CAM12  2026-05-01 03:06:00                37  Capivara  Mamífero           5       15.7 °C       98.6%
37           38     CAM09  2026-05-01 05:11:00                30  Capivara  Mamífero          11       18.3 °C       96.3%
45           46     CAM10  2026-05-01 06:04:00                 4  Capivara  Mamífero           7       18.5 °C       88.0%
47           48     CAM12  2026-05-01 06:08:00                24  Capivara  Mamífero           3       17.7 °C       99.0%
49           50     CAM05  2026-05-01 06:31:00                53  Capivara  Mamífero           5       21.0 °C       91.7%
50           51     CAM09  2026-05-01 06:44:00                11  Capivara  Mamífero           6       18.2 °C       97.1%
55           56     CAM07  2026-05-01 07:13:00                16  Capivara  Mamífero           6       19.6 °C       84.1%
56           57     CAM07  2026-05-01 07:24:00                18  Capivara  Mamífero           6       17.5 °C       85.2%
62           63     CAM10  2026-05-01 08:01:00                 6  Capivara  Mamífero          10       21.9 °C       94.9%

Média de Indivíduos por Espécie

In [30]:
round(dt[(dt.especie=='Capivara')].individuos.mean(),2)

np.float64(5.95)

In [75]:
capi_so_qtd = dt[(dt.especie=='Capivara') & (dt.individuos==1)]['id_camera'].count()
capi_so_qtd
capi_so = dt[(dt.especie=='Capivara') & (dt.individuos==1)][['id_camera','individuos','data_hora_inicio']]
print("Registros de Inivíduos Solitários =", capi_so_qtd)
display(capi_so)

Registros de Inivíduos Solitários = 6

     id_camera  individuos     data_hora_inicio
1973     CAM05           1  2026-05-12 18:15:00
2194     CAM06           1  2026-05-14 02:40:00
3972     CAM02           1  2026-05-24 17:04:00
4363     CAM05           1  2026-05-27 03:10:00
4556     CAM05           1  2026-05-28 07:20:00
4954     CAM10           1  2026-05-30 16:50:00

In [111]:
capi_grp_qtd = dt[(dt.especie=='Capivara') & (dt.individuos>1)]['id_camera'].count()
capi_grp_qtd
capi_grp = dt[
    (dt.especie=='Capivara') & (dt.individuos>1)][
        ['id_camera','individuos','data_hora_inicio']
        ].sort_values(by='individuos', ascending=False)
print("Registros de Inivíduos em Grupos =", capi_grp_qtd)
display(capi_grp.head(10))

Registros de Inivíduos em Grupos = 725

     id_camera  individuos     data_hora_inicio
1067     CAM10          14  2026-05-07 10:58:00
1647     CAM08          14  2026-05-10 16:36:00
633      CAM12          13  2026-05-04 19:31:00
935      CAM10          13  2026-05-06 17:33:00
4942     CAM12          13  2026-05-30 15:16:00
3898     CAM09          12  2026-05-24 06:41:00
3307     CAM12          12  2026-05-20 15:44:00
3933     CAM06          12  2026-05-24 11:48:00
2129     CAM06          12  2026-05-13 15:55:00
494      CAM12          12  2026-05-04 01:52:00

Quantidade de Grupos encontrado

In [117]:
grupos = capi_grp['individuos'].value_counts().sort_index().reset_index()
grupos.columns = ['Individuos', 'Qtd_Registros']
display(grupos)

print("Total:", len(grupos))

    Individuos  Qtd_Registros
0            2             23
1            3             63
2            4            100
3            5            129
4            6            128
5            7            120
6            8             79
7            9             40
8           10             23
9           11             10
10          12              5
11          13              3
12          14              2

Total: 13